name: Cargo Bump
description: Bump Cargo.toml version
author: tj-actions
inputs:
  version:
    description: 'Semver Version to bump to. (Default: the diff between the current tag and the previous tag)'
    required: false
    default: ''
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

outputs:
  release_type:
    description: 'The difference between two versions by the release type (major, minor, patch)'
    value: ${{ steps.semver-diff.outputs.release_type }}
  new_version:
    description: 'The current project version'
    value: ${{ steps.semver-diff.outputs.new_version }}
  old_version:
    description: 'The previous project version'
    value: ${{ steps.semver-diff.outputs.old_version }}

runs:
  using: 'composite'
  steps:
    - name: Run semver-diff
      id: semver-diff
      uses: tj-actions/semver-diff@v2
      with:
        initial_release_type: ${{ inputs.version }}
    - name: Install stable toolchain
      if: steps.semver-diff.outputs.release_type != '' || inputs.version != ''
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v2
    - name: Bump Cargo.toml version
      shell: bash
      if: steps.semver-diff.outputs.release_type != '' || inputs.version != ''
      working-directory: ${{ inputs.working-directory }}
      run: |
        cargo install cargo-bump
        if [[ -z "${{ inputs.version }}" ]]; then
          cargo bump ${{ steps.semver-diff.outputs.release_type }}
        else
          cargo bump ${{ inputs.version }}
        fi
        cargo update --workspace
branding:
  icon: check-square
  color: white
