name: Cargo Bump
description: Bump Cargo.toml version
author: tj-actions
inputs:
  release_type:
    description: 'The release type (major, minor, patch). (Default: the diff between the current tag and the previous tag)'
    required: false
    default: ''
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

outputs:
  release_type:
    description: 'The difference between two versions by the release type (major, minor, patch)'
    value: ${{ steps.semver-diff.outputs.release_type }}
  new_version:
    description: 'The current project version'
    value: ${{ steps.semver-diff.outputs.new_version }}
  old_version:
    description: 'The previous project version'
    value: ${{ steps.semver-diff.outputs.old_version }}

runs:
  using: 'composite'
  steps:
    - name: Run semver-diff
      id: semver-diff
      uses: tj-actions/semver-diff@v2
      with:
        initial_release_type: ${{ inputs.release_type }}
    - name: Install stable toolchain
      if: steps.semver-diff.outputs.release_type != '' || inputs.release_type != ''
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions/cache@v3
      if: steps.semver-diff.outputs.release_type != '' || inputs.release_type != ''
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-cargo-bump
    - name: Bump Cargo.toml version
      shell: bash
      if: steps.semver-diff.outputs.release_type != '' || inputs.release_type != ''
      working-directory: ${{ inputs.working-directory }}
      run: |
        cargo install cargo-bump
        if [[ -z "${{ inputs.release_type }}" ]]; then
          cargo bump ${{ steps.semver-diff.outputs.release_type }}
        else
          cargo bump ${{ inputs.release_type }}
        fi
        cargo update --workspace
branding:
  icon: check-square
  color: white
